package checker

const (
	severityDeprecated = "deprecated"
	severityWarning    = "warning"
	severityError      = "error"

	methodGet  = "GET"
	methodHead = "HEAD"

	headerAccessControlAllowOrigin      = "Access-Control-Allow-Origin"
	headerCacheControl                  = "Cache-Control"
	headerContentSecurityPolicy         = "Content-Security-Policy"
	headerContentType                   = "Content-Type"
	headerCrossOriginEmbedderPolicy     = "Cross-Origin-Embedder-Policy"
	headerCrossOriginOpenerPolicy       = "Cross-Origin-Opener-Policy"
	headerCrossOriginResourcePolicy     = "Cross-Origin-Resource-Policy"
	headerETag                          = "ETag"
	headerExpectCT                      = "Expect-CT"
	headerPermissionsPolicy             = "Permissions-Policy"
	headerPragma                        = "Pragma"
	headerReferrerPolicy                = "Referrer-Policy"
	headerServer                        = "Server"
	headerStrictTransportSecurity       = "Strict-Transport-Security"
	headerXContentTypeOptions           = "X-Content-Type-Options"
	headerXFrameOptions                 = "X-Frame-Options"
	headerXPermittedCrossDomainPolicies = "X-Permitted-Cross-Domain-Policies"
	headerXXSSProtection                = "X-XSS-Protection"
	cspSourceSelf                       = "'self'"
	valueDeny                           = "DENY"
	valueSameOrigin                     = "same-origin"
	gradeAPlus                          = "A+"
	gradeA                              = "A"
	gradeAMinus                         = "A-"
	gradeBPlus                          = "B+"
	gradeB                              = "B"
	gradeBMinus                         = "B-"
	gradeCPlus                          = "C+"
	gradeC                              = "C"
	gradeCMinus                         = "C-"
	gradeDPlus                          = "D+"
	gradeD                              = "D"
	gradeDMinus                         = "D-"
	gradeF                              = "F"
)
